In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.datasets import make_classification

from imblearn.ensemble import BalancedRandomForestClassifier, EasyEnsembleClassifier
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('../Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

column = ['home_ownership','verification_status','issue_d','pymnt_plan','initial_list_status','next_pymnt_d','application_type','hardship_flag','debt_settlement_flag']
df = pd.get_dummies(df, columns=column)
df

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,1,1,0,1,0,1,1,0,1,1
5,25000.0,0.1797,634.43,90000.0,low_risk,18.49,1.0,1.0,14.0,0.0,...,1,1,0,1,0,1,1,0,1,1
6,20400.0,0.2000,540.48,51315.0,low_risk,25.63,0.0,2.0,8.0,1.0,...,1,1,0,1,0,1,1,0,1,1
7,10000.0,0.1557,349.46,66000.0,low_risk,9.00,0.0,0.0,11.0,0.0,...,1,1,0,1,0,1,1,0,1,1
8,14000.0,0.0881,443.96,45000.0,low_risk,10.24,0.0,1.0,9.0,0.0,...,1,1,1,0,0,1,1,0,1,1
9,10000.0,0.1474,345.39,63295.0,low_risk,39.34,0.0,0.0,27.0,0.0,...,1,1,0,1,0,1,1,0,1,1
10,8500.0,0.0819,267.11,75000.0,low_risk,17.31,0.0,2.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
11,10000.0,0.1171,330.76,54000.0,low_risk,21.49,0.0,2.0,18.0,0.0,...,1,1,0,1,0,1,1,0,1,1
12,30000.0,0.1033,642.30,100000.0,low_risk,8.00,0.0,0.0,4.0,0.0,...,1,1,0,1,0,1,1,0,1,1
13,15800.0,0.1640,387.60,62000.0,low_risk,8.44,0.0,1.0,5.0,0.0,...,1,1,0,1,0,1,1,0,1,1
14,18000.0,0.1557,433.63,60000.0,low_risk,62.80,0.0,0.0,9.0,0.0,...,1,1,0,1,0,1,0,1,1,1
15,40000.0,0.2250,1537.99,54000.0,low_risk,59.09,0.0,0.0,19.0,0.0,...,1,1,0,1,0,1,0,1,1,1
16,14400.0,0.1390,491.46,100350.0,low_risk,30.42,0.0,2.0,27.0,1.0,...,1,1,0,1,0,1,1,0,1,1
17,9600.0,0.0881,304.43,92000.0,low_risk,20.01,0.0,0.0,10.0,0.0,...,1,1,0,1,0,1,1,0,1,1
18,16000.0,0.1719,399.28,72500.0,low_risk,17.00,0.0,0.0,8.0,0.0,...,1,1,0,1,0,1,1,0,1,1
19,20000.0,0.0756,622.68,175000.0,low_risk,11.28,0.0,0.0,10.0,0.0,...,1,1,0,1,0,1,1,0,1,1
20,28000.0,0.1797,710.56,85000.0,low_risk,20.19,2.0,0.0,9.0,0.0,...,1,1,0,1,0,1,1,0,1,1
21,7500.0,0.0646,229.74,57500.0,low_risk,11.52,0.0,0.0,7.0,1.0,...,1,1,0,1,0,1,1,0,1,1
22,19000.0,0.1033,406.79,38700.0,low_risk,20.56,0.0,1.0,11.0,0.0,...,1,1,0,1,0,1,1,0,1,1
23,30000.0,0.0756,934.02,66600.0,low_risk,11.77,1.0,3.0,19.0,0.0,...,1,1,0,1,0,1,1,0,1,1
24,13975.0,0.1640,342.83,67000.0,low_risk,13.04,0.0,0.0,6.0,0.0,...,1,1,0,1,0,1,0,1,1,1
25,40000.0,0.1171,883.93,79000.0,low_risk,21.89,1.0,0.0,29.0,0.0,...,1,1,0,1,0,1,0,1,1,1
26,7500.0,0.0702,231.65,80000.0,low_risk,15.17,0.0,1.0,7.0,0.0,...,1,1,0,1,0,1,1,0,1,1
27,39475.0,0.1308,899.80,100000.0,low_risk,21.30,0.0,0.0,13.0,0.0,...,1,1,0,1,0,1,1,0,1,1
28,35000.0,0.0702,1081.02,50000.0,low_risk,38.93,0.0,0.0,14.0,0.0,...,1,1,0,1,0,1,0,1,1,1
29,7200.0,0.1557,251.61,130000.0,low_risk,22.33,0.0,0.0,29.0,0.0,...,1,1,0,1,0,1,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68787,3800.0,0.0819,119.42,23800.0,low_risk,20.55,0.0,0.0,6.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68788,21000.0,0.1797,758.89,46572.0,low_risk,32.90,0.0,2.0,24.0,1.0,...,0,1,1,0,0,1,1,0,1,1
68789,7800.0,0.1691,277.75,44000.0,low_risk,20.89,0.0,0.0,8.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68790,20000.0,0.1502,476.01,54000.0,low_risk,48.16,0.0,1.0,13.0,0.0,...,0,1,0,1,0,1,0,1,1,1
68791,40000.0,0.1691,992.17,12000.0,low_risk,147.10,0.0,1.0,12.0,1.0,...,0,1,1,0,0,1,0,1,1,1
68792,20000.0,0.0819,628.49,60000.0,low_risk,10.04,1.0,0.0,14.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68793,40000.0,0.1691,992.17,175000.0,low_risk,6.33,0.0,1.0,22.0,1.0,...,0,1,1,0,0,1,1,0,1,1
68794,35000.0,0.1502,1213.63,170000.0,low_risk,16.64,1.0,0.0,14.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68795,18000.0,0.1180,398.59,180000.0,low_risk,7.64,1.0,1.0,18.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68796,30000.0,0.1992,1113.69,52000.0,low_risk,24.05,0.0,0.0,10.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68797,35000.0,0.0756,1089.69,164200.0,low_risk,26.53,2.0,0.0,20.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68798,38675.0,0.0819,1215.33,125000.0,low_risk,21.03,0.0,0.0,10.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68799,6000.0,0.0819,188.55,30000.0,low_risk,14.60,0.0,0.0,6.0,1.0,...,0,1,0,1,0,1,1,0,1,1
68800,15000.0,0.1298,341.15,80000.0,low_risk,31.04,0.0,1.0,17.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68801,40000.0,0.0702,1235.45,150000.0,low_risk,15.24,0.0,0.0,19.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68802,25000.0,0.1502,866.88,60000.0,low_risk,18.70,2.0,0.0,15.0,1.0,...,0,1,1,0,0,1,1,0,1,1
68803,6900.0,0.1131,226.92,43000.0,low_risk,26.96,0.0,0.0,13.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68804,35000.0,0.1691,1246.28,180000.0,low_risk,33.49,5.0,0.0,15.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68805,40000.0,0.0881,1268.46,105000.0,low_risk,23.98,0.0,0.0,21.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68806,28000.0,0.1691,997.03,83000.0,low_risk,21.57,1.0,1.0,13.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68807,35000.0,0.0819,1099.85,75005.0,low_risk,36.34,0.0,1.0,17.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68808,10000.0,0.0819,314.25,47000.0,low_risk,12.51,0.0,0.0,16.0,1.0,...,0,1,0,1,0,1,1,0,1,1
68809,6500.0,0.1502,225.39,70000.0,low_risk,34.78,0.0,1.0,13.0,0.0,...,0,1,1,0,1,0,1,0,1,1
68810,9600.0,0.0756,298.89,64000.0,low_risk,14.27,0.0,1.0,13.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68811,10000.0,0.0646,306.31,98000.0,low_risk,22.41,1.0,0.0,16.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68812,10000.0,0.1502,346.76,26000.0,low_risk,9.60,0.0,0.0,9.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68813,12000.0,0.2727,368.37,63000.0,low_risk,29.07,0.0,0.0,8.0,0.0,...,0,1,0,1,0,1,1,0,1,1
68814,5000.0,0.1992,185.62,52000.0,low_risk,14.86,0.0,0.0,5.0,1.0,...,0,1,0,1,0,1,1,0,1,1
68815,40000.0,0.0646,1225.24,520000.0,low_risk,9.96,0.0,1.0,21.0,0.0,...,0,1,1,0,0,1,1,0,1,1
68816,16000.0,0.1131,350.36,72000.0,low_risk,7.02,2.0,0.0,12.0,1.0,...,0,1,0,1,0,1,1,0,1,1

# Split the Data into Training and Testing

In [6]:
# Create our features
X = df.drop(columns= "loan_status")

# Create our target
y = df["loan_status"]

In [7]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [8]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [9]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                   y, 
                                                random_state=1, 
                                                   stratify=y)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [10]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [11]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset

X_scaler = scaler.fit(X_train)

In [25]:
# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [13]:
# Resample the training data with the BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(n_estimators=100,random_state=1)
brf_model = brf.fit(X_train_scaled,y_train)

In [23]:
# Calculated the balanced accuracy score
predictions = brf_model.predict(X_test_scaled)
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score *100}")

Accuracy Score : 90.63644289450741

In [15]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

print("Confusion Matrix -->")
display(cm_df)

Confusion Matrix -->

          Predicted 0  Predicted 1
Actual 0           58           29
Actual 1         1582        15536

In [16]:
# Print the imbalanced classification report
print("Classification Report -->")
print(classification_report(y_test, predictions))

Classification Report -->
              precision    recall  f1-score   support

   high_risk       0.04      0.67      0.07        87
    low_risk       1.00      0.91      0.95     17118

    accuracy                           0.91     17205
   macro avg       0.52      0.79      0.51     17205
weighted avg       0.99      0.91      0.95     17205

In [17]:
# List the features sorted in descending order by feature importance
importances = brf_model.feature_importances_
sorted(zip(brf_model.feature_importances_, X.columns), reverse=True)

[(0.07376667607601396, 'total_rec_prncp'),
 (0.06390324452717588, 'total_rec_int'),
 (0.06073336071656837, 'total_pymnt_inv'),
 (0.05811195697921674, 'total_pymnt'),
 (0.04951778391272079, 'last_pymnt_amnt'),
 (0.02458051789018817, 'int_rate'),
 (0.020398879691407974, 'out_prncp'),
 (0.018625883307901298, 'dti'),
 (0.018378884967316288, 'max_bal_bc'),
 (0.017480030880564042, 'issue_d_Jan-2019'),
 (0.01698703048268034, 'installment'),
 (0.01661321625916749, 'annual_inc'),
 (0.01623198470200134, 'bc_util'),
 (0.015821923028819504, 'mths_since_recent_inq'),
 (0.015385686591272854, 'total_bc_limit'),
 (0.015337070167127763, 'out_prncp_inv'),
 (0.01506649550412446, 'avg_cur_bal'),
 (0.014926455495755147, 'issue_d_Mar-2019'),
 (0.014924489307566175, 'revol_bal'),
 (0.014583210727445232, 'mo_sin_old_rev_tl_op'),
 (0.01428231366275729, 'total_bal_ex_mort'),
 (0.014238473969302518, 'tot_cur_bal'),
 (0.014067369111282934, 'mo_sin_old_il_acct'),
 (0.01351439379612201, 'total_bal_il'),
 (0.013343855077273033, 'bc_open_to_buy'),
 (0.013138998568932102, 'il_util'),
 (0.013106005248709657, 'tot_hi_cred_lim'),
 (0.013009300843392654, 'all_util'),
 (0.012104219411815444, 'total_il_high_credit_limit'),
 (0.011927748948209041, 'num_rev_accts'),
 (0.011194718062040365, 'total_rev_hi_lim'),
 (0.01072808547266412, 'mths_since_recent_bc'),
 (0.010485766778776592, 'pct_tl_nvr_dlq'),
 (0.010480039757813501, 'total_acc'),
 (0.010433852907121713, 'mths_since_rcnt_il'),
 (0.010171477424921242, 'mo_sin_rcnt_rev_tl_op'),
 (0.00990081847673844, 'num_rev_tl_bal_gt_0'),
 (0.00982912014219909, 'loan_amnt'),
 (0.009709211384642156, 'inq_last_12m'),
 (0.00939406635676521, 'num_bc_tl'),
 (0.009390960836832822, 'num_op_rev_tl'),
 (0.008883434647669785, 'mo_sin_rcnt_tl'),
 (0.008287412625195438, 'num_actv_bc_tl'),
 (0.00794880573688952, 'total_cu_tl'),
 (0.007944596002325902, 'percent_bc_gt_75'),
 (0.007841727903546316, 'num_sats'),
 (0.007813875400824535, 'num_actv_rev_tl'),
 (0.007760323250042998, 'open_acc'),
 (0.007420667106687749, 'acc_open_past_24mths'),
 (0.007404967411706728, 'inq_fi'),
 (0.007339507170175945, 'num_il_tl'),
 (0.006876404000725424, 'open_il_24m'),
 (0.00678542812487817, 'num_bc_sats'),
 (0.006660043732852357, 'open_act_il'),
 (0.006599809671624734, 'open_rv_24m'),
 (0.006393774120528892, 'mort_acc'),
 (0.006391381020548387, 'total_rec_late_fee'),
 (0.006065825838862652, 'num_tl_op_past_12m'),
 (0.006004776142662084, 'open_acc_6m'),
 (0.005920335354841418, 'next_pymnt_d_Apr-2019'),
 (0.005413306654546768, 'open_rv_12m'),
 (0.005248840731650208, 'open_il_12m'),
 (0.00487120814476765, 'issue_d_Feb-2019'),
 (0.004802823221798599, 'next_pymnt_d_May-2019'),
 (0.0047562588132075015, 'inq_last_6mths'),
 (0.0045238834578884635, 'delinq_2yrs'),
 (0.0039029173953907185, 'num_accts_ever_120_pd'),
 (0.003789677267237295, 'tot_coll_amt'),
 (0.0020853638216694215, 'home_ownership_OWN'),
 (0.0020060097354201176, 'home_ownership_MORTGAGE'),
 (0.001984067551288744, 'verification_status_Source Verified'),
 (0.0018789153640443002, 'verification_status_Verified'),
 (0.0018544555674736187, 'verification_status_Not Verified'),
 (0.0016995259802440514, 'home_ownership_RENT'),
 (0.001520907850775936, 'pub_rec_bankruptcies'),
 (0.0014185754855487824, 'pub_rec'),
 (0.0013879548937552864, 'initial_list_status_f'),
 (0.001239058844214324, 'application_type_Individual'),
 (0.0011046122443753368, 'num_tl_90g_dpd_24m'),
 (0.000805030988421211, 'initial_list_status_w'),
 (0.000710297252940571, 'application_type_Joint App'),
 (0.0006949062181389056, 'collections_12_mths_ex_med'),
 (0.00013272979926763346, 'home_ownership_ANY'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'chargeoff_within_12_mths'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble Classifier

In [18]:
# Train the EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec_model = eec.fit(X_train_scaled,y_train)

In [19]:
# Calculated the balanced accuracy score
predictions = eec_model.predict(X_test_scaled)
eec_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score *100}")

Accuracy Score : 90.63644289450741

In [20]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

print("Confusion Matrix -->")
display(cm_df)

Confusion Matrix -->

          Predicted 0  Predicted 1
Actual 0           79            8
Actual 1          978        16140

In [21]:
# Print the imbalanced classification report
print("Classification Report -->")
print(classification_report(y_test, predictions))

Classification Report -->
              precision    recall  f1-score   support

   high_risk       0.07      0.91      0.14        87
    low_risk       1.00      0.94      0.97     17118

    accuracy                           0.94     17205
   macro avg       0.54      0.93      0.55     17205
weighted avg       0.99      0.94      0.97     17205